name: Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - master
    
jobs:
  notify:

    runs-on: ubuntu-latest

    steps:
      - name: notify merged
        if: github.event.pull_request.merged == true
        run: |
          echo 'it was merged successfully'
